4 - Analyzing and profiling tools
olezhko/.NET-Mentoring-Program-Intermediate-2023-Q1 pull request #4
Opened 2023-05-06 21:01 UTC by olezhko

2023-05-12 15:52 UTC, vlarkovich requested changes

2023-05-12 16:01 UTC, vlarkovich commented on 04.AnalyzingProfilingTools/DumpHomework/place.PNG
it is out of scope in the homework, but there are some interesting ways to actually fix this exe file, for example https://github.com/dnSpy/dnSpy, you can at least try if you want

2023-05-14 20:01 UTC, olezhko commented on 04.AnalyzingProfilingTools/Task1/Task1/Program.cs
> +    var passwordHash = Convert.ToBase64String(salt.Concat(hash).ToArray());
thanks. some of them I know.

2023-05-29 07:31 UTC, vlarkovich approved these changes

2023-05-29 19:28 UTC, merged